-- Team-scoped role assignments (captain, team_manager, etc.)
-- Mirrors the shape of event_user_roles but scopes a role to a specific team
-- (optionally within a specific event, since team membership/roles can change
-- season to season).

create table if not exists public.team_user_roles (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  role_id     bigint not null references public.roles(id) on delete cascade,
  team_id     uuid not null references public.teams(id) on delete cascade,
  event_id    uuid references public.events(id) on delete cascade,
  created_at  timestamptz not null default now(),
  granted_by  uuid references public.profiles(id),

  constraint team_user_roles_unique unique (user_id, role_id, team_id, event_id)
);

-- Postgres treats NULL as distinct in a unique constraint, so a separate
-- partial index is needed to prevent duplicate team-wide (no event) grants.
create unique index if not exists team_user_roles_unique_no_event
  on public.team_user_roles (user_id, role_id, team_id)
  where event_id is null;

create index if not exists team_user_roles_team_id_idx on public.team_user_roles (team_id);
create index if not exists team_user_roles_user_id_idx on public.team_user_roles (user_id);
create index if not exists team_user_roles_event_id_idx on public.team_user_roles (event_id);

-- Row Level Security
alter table public.team_user_roles enable row level security;

-- Public/anon read (mirrors the read-open pattern used for other role tables
-- that the client needs to resolve display info from). Adjust if team role
-- assignments should not be publicly readable.
create policy "team_user_roles_select_all"
  on public.team_user_roles
  for select
  using (true);

-- Only users with role_edit / admin_override permission may manage grants.
-- Adjust the permission check to match how other write policies express this
-- in your schema (e.g. a has_permission() helper function, if one exists).
create policy "team_user_roles_insert_admin"
  on public.team_user_roles
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.user_roles ur
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id
      where ur.user_id = auth.uid()
        and p.key in ('role_edit', 'admin_override')
    )
  );

create policy "team_user_roles_delete_admin"
  on public.team_user_roles
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.user_roles ur
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id
      where ur.user_id = auth.uid()
        and p.key in ('role_edit', 'admin_override')
    )
  );
